# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.6.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QMainWindow, QMenu, QMenuBar,
    QPushButton, QSizePolicy, QStatusBar, QWidget)

from analoggaugewidget import AnalogGaugeWidget

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet(u"/*\n"
"ABOUT\n"
"===========================================================\n"
"version 1.7a\n"
"QT theme (stylesheet) specially developed for FreeCAD (http://www.freecadweb.org/).\n"
"It might work with other software that uses QT styling.\n"
"\n"
"\n"
"LICENSE\n"
"===========================================================\n"
"Copyright (c) 2015 Pablo Gil Fern\u00e1ndez\n"
"The stylesheet barely uses code from Colin Duquesnoy \"generic QT stylesheet\"\n"
"\n"
"This work is licensed under the Creative Commons Attribution-ShareAlike 4.0 International License.\n"
"To view a copy of this license, visit http://creativecommons.org/licenses/by-sa/4.0/.\n"
"\n"
" \n"
"\n"
"CUSTOMIZATION\n"
"===========================================================\n"
"If you would like to change the overall look/style of the theme, just find and replace following colors in the whole file:\n"
"    background darker = #4d4e51\n"
"    background dark and slighly darker = #5d5e61\n"
"    background dark = #6d6e71\n"
"    background n"
                        "ormal and slighly darker = #797b7f\n"
"    background normal = #85878a\n"
"    background light = #9a9b9e\n"
"    background lighter = #c7c7c9\n"
"\n"
"    lists background = #bdc1c9\n"
"    lists background (alternate) = #b3b8bf\n"
"    lists backgrounds selection = #abb0b7\n"
"\n"
"    foreground = white\n"
"\n"
"    selection darker = #1b3774\n"
"    selection dark = #3874f2\n"
"    selection normal = #5e90fa\n"
"    selection inbetween normal and light = #6f9efa (used to build SpinBoxes)\n"
"    selection light = #7cabf9\n"
"    selection lighter = #adc5ed\n"
" \n"
"*/\n"
"\n"
"/* RESET EVERYTHING */\n"
"QAbstractScrollArea,QCheckBox,QColumnView,QComboBox,QDateEdit,QDateTimeEdit,QDialog,QDialogButtonBox,QDockWidget,QDoubleSpinBox,QFrame,QGroupBox,QHeaderView,QLabel,QLineEdit,QListView,QListWidget,QMainWindow,QMenu,QMenuBar,QMessageBox,QProgressBar,QPushButton,QRadioButton,QScrollBar,QSizeGrip,QSlider,QSpinBox,QSplitter,QStatusBar,QTabBar,QTabWidget,QTableView,QTableWidget,QTextEdit,QTimeEdit,QToolBar,QTool"
                        "Button,QToolBox,QToolTip,QTreeView,QTreeWidget,QWidget {\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"    border: 0px;\n"
"    border-style: none;\n"
"    background-color: #85878a; /* set with default background color */\n"
"}\n"
"\n"
"QMdiArea[showImage=\"true\"] {\n"
"    background-image: url(icons/background_freecad.png);\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"}\n"
"\n"
"QProgressBar,\n"
"QProgressBar:horizontal {\n"
"    background: #bdc1c9;\n"
"    border: 1px solid #6d6e71;\n"
"    text-align: center;\n"
"    padding: 1px;\n"
"    border-radius: 4px;\n"
"}\n"
"QProgressBar::chunk,\n"
"QProgressBar::chunk:horizontal {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.545, x2:1, y2:0, stop:0 #3874f2, stop:1 #5e90fa);\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QToolTip {\n"
"    background-color: #4d4e51;\n"
"    color: white;\n"
"    padding: 4px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QWidget {\n"
"    color: #4d4e51;\n"
"    background-color:"
                        " #85878a;\n"
"    background-clip: border;\n"
"    border-image: none;\n"
"    outline: 0;\n"
"}\n"
"\n"
"QWidget:focus {\n"
"    border: 1px solid #4d4e51;\n"
"}\n"
"\n"
"QWidget:disabled {\n"
"    color: #9a9b9e;\n"
"    background-color: #4d4e51; /* same as QMenu background-color */\n"
"}\n"
"\n"
"QMenuBar {\n"
"    color: #c7c7c9;\n"
"    background-color: #797b7f;\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"    background-color: #797b7f;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    color: #1b3774;\n"
"    border: 1px solid #5e90fa;\n"
"    background-color: #5e90fa;\n"
"}\n"
"\n"
"QMenuBar::item:pressed {\n"
"    color: #1b3774;\n"
"    border: 1px solid #7cabf9;\n"
"    background-color: #7cabf9;\n"
"    margin-bottom:-1px;\n"
"    padding-bottom:1px;\n"
"}\n"
"\n"
"QMenu {\n"
"    color: #c7c7c9;\n"
"    background-color: #4d4e51;\n"
"    margin: 2px;\n"
"    border: 1px solid transparent;\n"
"}\n"
"\n"
"QMenu::icon {\n"
"    margin: 5px;\n"
"    border-style: none;\n"
"}\n"
"\n"
"QMenu::right-arrow {\n"
" "
                        "   image:url(icons/right_arrow_light.png);\n"
"}\n"
"\n"
"QMenu::item {\n"
"    color: #c7c7c9;\n"
"    background-color: #4d4e51;\n"
"    padding: 2px 30px 2px 30px;\n"
"    border: 1px solid #4d4e51; /* reserve space for selection border */\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    color: #1b3774;\n"
"    background-color: #7cabf9;\n"
"}\n"
"\n"
"QMenu::separator {\n"
"    height: 1px;\n"
"    background-color: #6d6e71;\n"
"    margin-top: 2px;\n"
"    margin-bottom: 2px;\n"
"    margin-left: 6px;\n"
"    margin-right: 6px;\n"
"}\n"
"\n"
"QMenu::indicator:non-exclusive {\n"
"    color: #c7c7c9;\n"
"    background-color: #9a9b9e;\n"
"    border: 1px solid #4d4e51;\n"
"    width: 11px;\n"
"    height: 11px;\n"
"    border-radius:2px;\n"
"}\n"
"\n"
"QMenu::indicator:non-exclusive:checked {\n"
"    background-color: #3874f2;\n"
"    border: 1px solid #1b3774;\n"
"    image:url(icons/checkbox_light.png);\n"
"}\n"
"\n"
"QGroupBox {\n"
"    color: #4d4e51;\n"
"    font-weight: bold;\n"
"    border:1px solid blu"
                        "e;\n"
"    border-radius: 4px;\n"
"    margin-top: 20px;\n"
"    border-color: rgba(0, 0, 0, 20); /* lighter than \"QGroupBox\" border-color */\n"
"    background-color: rgba(255, 255, 255, 15);\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"    padding-top: 10px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QAbstractScrollArea {\n"
"    border-radius: 2px;\n"
"    border: 1px solid #3A3939;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QAbstractScrollArea::corner {\n"
"    border: none;\n"
"    background-color: #85878a;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    height: 15px;\n"
"    margin: 3px 15px 3px 15px;\n"
"    border: 1px transparent #4d4e51;\n"
"    border-radius: 4px;\n"
"    background-color: #4d4e51;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: #6d6e71;\n"
"    min-width: 5px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBa"
                        "r::add-line:horizontal {\n"
"    margin: 1px 3px 0px 3px; /* 1px to correctly fit the 10px width image */\n"
"    border-image: url(icons/right_arrow_light.png);\n"
"    width: 6px;\n"
"    height: 10px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    margin: 1px 3px 0px 3px; /* 1px to correctly fit the 10px width image */\n"
"    border-image: url(icons/left_arrow_light.png);\n"
"    height: 10px;\n"
"    width: 6px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal:hover,\n"
"QScrollBar::add-line:horizontal:on {\n"
"    border-image: url(icons/right_arrow_lighter.png);\n"
"}\n"
"\n"
"\n"
"QScrollBar::sub-line:horizontal:hover,\n"
"QScrollBar::sub-line:horizontal:on {\n"
"    border-image: url(icons/left_arrow_lighter.png);\n"
"}\n"
"\n"
"QScrollBar::up-arrow:horizontal,\n"
"QScrollBar::down-arrow:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"\n"
"QScrollBa"
                        "r::add-page:horizontal,\n"
"QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    background-color: #4d4e51;\n"
"    width: 15px;\n"
"    margin: 15px 3px 15px 3px;\n"
"    border: 1px transparent #4d4e51;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background-color: #6d6e71;\n"
"    min-height: 5px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    margin: 3px 0px 3px 1px; /* 1px to correctly fit the 10px width image */\n"
"    border-image: url(icons/up_arrow_light.png);\n"
"    height: 6px;\n"
"    width: 10px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    margin: 3px 0px 3px 1px; /* 1px to correctly fit the 10px width image */\n"
"    border-image: url(icons/down_arrow_light.png);\n"
"    height: 6px;\n"
"    width: 10px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QSc"
                        "rollBar::sub-line:vertical:hover,\n"
"QScrollBar::sub-line:vertical:on {\n"
"    border-image: url(icons/up_arrow_lighter.png);\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:hover,\n"
"QScrollBar::add-line:vertical:on {\n"
"    border-image: url(icons/down_arrow_lighter.png);\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical,\n"
"QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:vertical,\n"
"QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QTextEdit {\n"
"    color: #4d4e51;\n"
"    background-color: #bdc1c9;\n"
"    border: 1px solid #6d6e71;\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QPlainTextEdit {\n"
"    color: #4d4e51;\n"
"    background-color: #bdc1c9;\n"
"    border-radius: 2px;\n"
"    border: 1px solid #6d6e71;\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QSizeGrip {\n"
"    image: url(icons/sizegrip_light.png);\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    background-color: transparent;\n"
"}\n"
""
                        "\n"
"QRadioButton::indicator:unchecked{\n"
"    color: #4d4e51;\n"
"    background-color: #9a9b9e;\n"
"    border: 1px solid #4d4e51;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: #3874f2;\n"
"    border: 1px solid #1b3774;\n"
"    image:url(icons/radiobutton_light.png);\n"
"}\n"
"\n"
"QCheckBox,\n"
"QRadioButton,\n"
"QCheckBox:disabled,\n"
"QRadioButton:disabled {\n"
"    color: #4d4e51;\n"
"    padding: 3px;\n"
"    outline: none;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QCheckBox::indicator,\n"
"QGroupBox::indicator {\n"
"    color: #c7c7c9;\n"
"    background-color: #9a9b9e;\n"
"    border: 1px solid #4d4e51;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 11px;\n"
"    height: 11px;\n"
"    border-radius:2px;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 11px;\n"
"    height: 11px;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QRadioButton::indicator:pressed,\n"
"QCheckBox::indicator:pressed,\n"
"QCheckBox::indicator:non-exclusive:checked:pressed,\n"
""
                        "QCheckBox::indicator:indeterminate:pressed,\n"
"QCheckBox::indicator:checked:pressed {\n"
"    border-color: #adc5ed;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked,\n"
"QGroupBox::indicator:checked {\n"
"    background-color: #3874f2;\n"
"    border: 1px solid #1b3774;\n"
"    image:url(icons/checkbox_light.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:disabled,\n"
"QRadioButton::indicator:disabled {\n"
"    border: 1px solid #6d6e71;\n"
"}\n"
"\n"
"QCheckBox:disabled,\n"
"QRadioButton::indicator:disabled {\n"
"    color: #6d6e71;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QCheckBox::indicator:disabled,\n"
"QGroupBox::indicator:disabled,\n"
"QMenu::indicator:non-exclusive:disabled {\n"
"    background-color: #85878a;\n"
"}\n"
"\n"
"QCheckBox::indicator:indeterminate {\n"
"    background-color: #3874f2;\n"
"    border: 1px solid #1b3774;\n"
"    image: url(icons/checkbox_indeterminate_light.png);\n"
"}\n"
"\n"
"QCheckBox:focus,\n"
"QRadioButton:focus {\n"
"    border: none;\n"
"}\n"
"\n"
"QFrame,\n"
"QFram"
                        "e:pressed,\n"
"QFrame:focus,\n"
"QFrame:on {\n"
"    border: 1px solid #85878a;\n"
"    border-radius: 3px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"/* border and background of QComboBox drop-down */\n"
"QComboBox QFrame,\n"
"QComboBox QFrame:pressed,\n"
"QComboBox QFrame:focus,\n"
"QComboBox QFrame:on {\n"
"    border: 1px solid #4d4e51;\n"
"    background-color: #4d4e51;\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QFrame[frameShape=\"0\"] {\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QFrame[height=\"3\"],\n"
"QFrame[width=\"3\"] {\n"
"    border-color: transparent;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QFrame[height=\"3\"] {\n"
"    border-top-color: #6d6e71;\n"
"}\n"
"\n"
"QFrame[width=\"3\"] {\n"
"    border-left-color: #6d6e71;\n"
"}\n"
"\n"
"QPushButton {\n"
"    color: #c7c7c9;\n"
"    text-align: center;\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.545, x2:1, y2:0, stop:0 #6d6e71, stop:1 #85878a);\n"
"    border: 1px solid #4d4e51;\n"
"    padding: 5px 12px "
                        "5px 12px;\n"
"    margin: 4px 8px 4px 8px;\n"
"    border-radius: 3px;\n"
"    min-width: 14px;\n"
"    min-height: 14px;\n"
"}\n"
"\n"
"QPushButton:hover,\n"
"QPushButton:focus {\n"
"    color: white;\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.545, x2:1, y2:0, stop:0 #3874f2, stop:1 #5e90fa);\n"
"    border-color: #3874f2;\n"
"}\n"
"\n"
"QPushButton:disabled,\n"
"QPushButton:disabled:checked {\n"
"    color: #6d6e71;\n"
"    background-color: #85878a;\n"
"    border-color: #6d6e71;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3874f2;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #5e90fa;\n"
"    border-color: #3874f2;\n"
"}\n"
"\n"
"/* Color Buttons */\n"
"Gui--ColorButton,\n"
"Gui--ColorButton:disabled {\n"
"    border-color: transparent;\n"
"    background-color: transparent;\n"
"    height: 24px;\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"Gui--ColorButton:hover {\n"
"    border-color: #797b7f;\n"
"    background-color: #797b7f;\n"
"}\n"
""
                        "\n"
"/* Buttons inside the toolbar */\n"
"QToolBar QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.545, x2:1, y2:0, stop:0 #797b7f, stop:1 #85878a);\n"
"    border: 1px solid #6d6e71;\n"
"    min-width: 22px;\n"
"    min-height: 22px;\n"
"    margin-left: 2px;\n"
"    margin-right: 2px;\n"
"    margin-bottom: 3px; /*bigger margin to correctly separate buttons inside a vertical toolbar */\n"
"    margin-top: 1px;\n"
"    padding: 1px;\n"
"}\n"
"\n"
"QToolBar QPushButton:hover,\n"
"QToolBar QPushButton:focus {\n"
"    color: #c7c7c9;\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.545, x2:1, y2:0, stop:0 #797b7f, stop:1 #85878a);\n"
"    border: 1px solid #4d4e51;\n"
"}\n"
"\n"
"QToolBar QPushButton:disabled,\n"
"QToolBar QPushButton:disabled:checked {\n"
"    background-color: #85878a;\n"
"    border-color: #797b7f;\n"
"}\n"
"\n"
"QToolBar QPushButton:pressed {\n"
"    background-color: #6d6e71;\n"
"    border-color: #6d6e71;\n"
"}\n"
"\n"
"QToolBar QPushButton:ch"
                        "ecked {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.8, x2:1, y2:0, stop:0 #5e90fa, stop:1 #7cabf9);\n"
"    border-color: #5e90fa;\n"
"}\n"
"\n"
"QToolBar QPushButton:checked:hover,\n"
"QToolBar QPushButton:checked:focus {\n"
"    color: #c7c7c9;\n"
"    border: 1px solid #3874f2;\n"
"}\n"
"\n"
"QToolBar {\n"
"    border: 1px transparent #393838;\n"
"    background-color: #85878a;\n"
"    font-weight: bold;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"QToolBar::handle:horizontal {\n"
"    background-image: url(icons/Hmovetoolbar_dark.png);\n"
"    width: 10px;\n"
"    margin: 6px 2px 6px 2px;\n"
"    background-position: top right;\n"
"    background-repeat: repeat-y;\n"
"}\n"
"\n"
"QToolBar::handle:vertical {\n"
"    background-image: url(icons/Vmovetoolbar_dark.png);\n"
"    height: 10px;\n"
"    margin: 2px 6px 2px 6px;\n"
"    background-position: left bottom;\n"
"    background-repeat: repeat-x;\n"
"}\n"
"\n"
"QToolBar::separator:horizontal {\n"
"    background-image: url"
                        "(icons/separtoolbar_dark.png);\n"
"    width: 10px;\n"
"    margin: 6px 2px 6px 2px;\n"
"    background-position: center center;\n"
"    background-repeat: repeat-y;\n"
"}\n"
"\n"
"QToolBar::separator:vertical {\n"
"    background-image: url(icons/separtoolbar_dark.png);\n"
"    height: 10px;\n"
"    margin: 2px 6px 2px 6px;\n"
"    background-position: center center;\n"
"    background-repeat: repeat-x;\n"
"}\n"
"\n"
"QStackedWidget {\n"
"    background-color: #85878a;\n"
"    border: 1px transparent #85878a;\n"
"}\n"
"\n"
"QAbstractSpinBox {\n"
"    color: #c7c7c9;\n"
"    border: 1px solid #6d6e71; /* border top color defined after QAbstractSpinBox, QLineEdit and QComboBox */\n"
"    background-color: #6d6e71;\n"
"    selection-color: white;\n"
"    selection-background-color: #5e90fa;\n"
"}\n"
"\n"
"QAbstractSpinBox:disabled {\n"
"    color: #9a9b9e;\n"
"    background-color: #797b7f;\n"
"    border-color: #797b7f;\n"
"}\n"
"\n"
"QAbstractSpinBox:up-button {\n"
"    background-color: qlineargradient(spread"
                        ":pad, x1:1, y1:0.8, x2:1, y2:0, stop:0 #6f9efa, stop:1 #7cabf9);\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: top right;\n"
"    border-top-right-radius: 3px;\n"
"    height: 13px;\n"
"    width: 20px;\n"
"}\n"
"\n"
"QAbstractSpinBox:down-button {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.8, x2:1, y2:0, stop:0 #5e90fa, stop:1 #6f9efa);\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: bottom right;\n"
"    border-bottom-right-radius: 3px;\n"
"    height: 13px;\n"
"    width: 20px;\n"
"}\n"
"\n"
"QAbstractSpinBox:up-button:disabled,\n"
"QAbstractSpinBox:down-button:disabled {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QAbstractSpinBox::up-arrow {\n"
"    image: url(icons/up_arrow_light.png);\n"
"    top: 0px; /* fix simetry between up and down images */\n"
"}\n"
"\n"
"QAbstractSpinBox::up-arrow:hover {\n"
"    image: url(icons/up_arrow_lighter.png);\n"
"}\n"
"\n"
"QAbstractSpinBox::up-arrow:off {\n"
"    image: url(icons/up_arrow_disabled_dark.p"
                        "ng);\n"
"}\n"
"\n"
"QAbstractSpinBox::up-arrow:disabled {\n"
"    image: none;\n"
"}\n"
"\n"
"QAbstractSpinBox::down-arrow {\n"
"    image: url(icons/down_arrow_light.png);\n"
"    bottom: -2px; /* fix simetry between up and down images */\n"
"}\n"
"QAbstractSpinBox::down-arrow:hover {\n"
"    image: url(icons/down_arrow_lighter.png);\n"
"}\n"
"\n"
"QAbstractSpinBox::down-arrow:off {\n"
"    image: url(icons/down_arrow_disabled_dark.png);\n"
"}\n"
"\n"
"QAbstractSpinBox::down-arrow:disabled {\n"
"    image: none;\n"
"}\n"
"\n"
"QToolBar QAbstractSpinBox {\n"
"    margin-top: 0px;\n"
"    margin-bottom: 0px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    color: #c7c7c9;\n"
"    background-color: #6d6e71;\n"
"    selection-color: white;\n"
"    selection-background-color: #5e90fa;\n"
"    /* Padding and margin defined */\n"
"    border-style: solid;\n"
"    border: 1px solid #6d6e71; /* border top color defined after QAbstractSpinBox, QLineEdit and QComboBox */\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QAbstractSpinBox:foc"
                        "us,\n"
"QLineEdit:focus,\n"
"QComboBox:focus {\n"
"    border-color: #7cabf9;\n"
"}\n"
"\n"
"QComboBox {\n"
"    color: #c7c7c9;\n"
"    background-color: #6d6e71;\n"
"    selection-color: white;\n"
"    selection-background-color: #5e90fa;\n"
"    border: 1px solid #6d6e71; /* border top color defined after QAbstractSpinBox, QLineEdit and QComboBox */\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QComboBox:on {\n"
"    color: white;\n"
"    background-color: #6d6e71;\n"
"    border-color: #7cabf9;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top right;\n"
"    width: 20px;\n"
"    border-left-width: 1px;\n"
"    border-left-color: transparent;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.8, x2:1, y2:0, stop:0 #5e90fa, stop:1 #7cabf9);\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(icons/down_arrow_light.png);\n"
"}"
                        "\n"
"\n"
"QComboBox::down-arrow:on,\n"
"QComboBox::down-arrow:hover,\n"
"QComboBox::down-arrow:focus {\n"
"    image: url(icons/down_arrow_lighter.png);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    color: #c7c7c9;\n"
"    background-color: #4d4e51;\n"
"    border-radius: 3px;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"    border: none;\n"
"}\n"
"\n"
"/* Common parameters for QAbstractSpinBox, QLineEdit and QComboBox */\n"
"QSpinBox,\n"
"QDoubleSpinBox,\n"
"QAbstractSpinBox,\n"
"QLineEdit,\n"
"QComboBox {\n"
"    border-top-color: #5d5e61; /* Creates an inset effect inside the elements */\n"
"    padding: 2px 6px 2px 6px; /* This makes text colour work on QComboBox */\n"
"    margin: 0px 2px 0px 2px;\n"
"    min-width: 70px; /* it was 120 because of QCombobox... */\n"
"    border-radius: 3px;\n"
"}\n"
"/* end Common parameters */\n"
"\n"
"QAbstractItemView {\n"
"    color: #4d4e51;\n"
"    alternate-background-color: #b3b8bf; /* related with QListView background  */\n"
"    border: 1px solid #4d4e51"
                        ";\n"
"    border-radius: 3px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"/* hack to deactivate changing background color when focus (due to QFrame generic transparent color) */\n"
"QAbstractItemView:selected,\n"
"QAbstractItemView:on,\n"
"QAbstractItemView:focus {\n"
"    background-color: #bdc1c9; /* same as QTable background color */\n"
"}\n"
"\n"
"/* hack to hide weird redundant information inside the value of a Placement cell */\n"
"QTreeView QLabel,\n"
"QTreeView QLabel:disabled {\n"
"    color: transparent;\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 0px;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"QTreeView QLineEdit {\n"
"    color: #c7c7c9;\n"
"    border-color: #6d6e71;\n"
"    background-color: #6d6e71;\n"
"    selection-color: white;\n"
"    selection-background-color: #5e90fa;\n"
"}\n"
"\n"
"/* hack to hide non editable cells inside Property values */\n"
"QTreeView QLineEdit:read-only,\n"
"QTreeView QLineEdit:disabled,\n"
"QTreeView QAbstractSpinBox:"
                        "read-only,\n"
"QTreeView QAbstractSpinBox:disabled {\n"
"    color: transparent;\n"
"    border-color: transparent;\n"
"    background-color: transparent;\n"
"    selection-color: transparent;\n"
"    selection-background-color: transparent;\n"
"}\n"
"\n"
"/* hack to disable margin inside Property values to following elements */\n"
"QTreeView QSpinBox,\n"
"QTreeView QDoubleSpinBox,\n"
"QTreeView QAbstractSpinBox,\n"
"QTreeView QLineEdit,\n"
"QTreeView QComboBox {\n"
"    margin-left: 0px;\n"
"    margin-right: 0px;\n"
"}\n"
"\n"
"/* Pushbutton style for \"...\" inside Placement cell which launches Placement tool */\n"
"QTreeView QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.545, x2:1, y2:0, stop:0 #6d6e71, stop:1 #85878a);\n"
"    border-top: none;\n"
"    border-bottom: none;\n"
"    border-right: none;\n"
"    border-left: 1px solid #6d6e71;\n"
"    border-radius: 0px;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"    height: 24px;\n"
"}\n"
"\n"
"/* Color Buttons inside the "
                        "\"Properties window\" */\n"
"QAbstractItemView Gui--ColorButton {\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"    height: 10px;\n"
"}\n"
"\n"
"QAbstractItemView QPushButton:hover {\n"
"    color: white;\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.545, x2:1, y2:0, stop:0 #3874f2, stop:1 #5e90fa);\n"
"    border-color: #3874f2;\n"
"}\n"
"\n"
"QAbstractItemView QPushButton:disabled {\n"
"    color: transparent;\n"
"    background-color: transparent;\n"
"    border-color: transparent;\n"
"}\n"
"\n"
"QLabel {\n"
"    border: 0px solid #4d4e51;\n"
"}\n"
"\n"
"QTabWidget{\n"
"    border: none;\n"
"}\n"
"\n"
"QTabWidget:focus {\n"
"    border: none;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: none;\n"
"    padding: 0px;\n"
"    background-color: #85878a;\n"
"    position: absolute;\n"
"    top: -15px;\n"
"    padding-top: 15px;\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"    alignment: center;\n"
"}\n"
"\n"
"QTabBar {\n"
"    qproperty-drawBase: 0;\n"
"    left: 5px;\n"
"    background-color"
                        ": transparent;\n"
"}\n"
"\n"
"QTabBar:focus {\n"
"    border: 0px transparent black;\n"
"}\n"
"\n"
"QTabBar::close-button {\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"    border-radius: 2px;\n"
"    background-image: url(icons/close_dark.png);\n"
"    background-position: center center;\n"
"    background-repeat: none;\n"
"}\n"
"\n"
"QTabBar::close-button:hover {\n"
"    background-color: #7cabf9;\n"
"}\n"
"\n"
"QTabBar::close-button:pressed {\n"
"    background-color: #adc5ed;\n"
"}\n"
"\n"
"QTabBar::scroller { /* the width of the scroll buttons */\n"
"    width: 20px;\n"
"}\n"
"\n"
"/* the scroll buttons are tool buttons */\n"
"QTabBar QToolButton,\n"
"QTabBar QToolButton:hover { \n"
"    margin-top: 4px;\n"
"    margin-bottom: 4px;\n"
"    margin-left: 0px;\n"
"    margin-right: 0px;\n"
"    padding: 0px;\n"
"    border: none;\n"
"    background-color: #85878a;\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"QTabBar QToolButton::right-arrow:enabled {\n"
"     image: url(icons/right_arrow_light.png);\n"
"}\n"
""
                        "\n"
"QTabBar QToolButton::right-arrow:disabled,\n"
"QTabBar QToolButton::right-arrow:off {\n"
"     image: url(icons/right_arrow_disabled_dark.png);\n"
"}\n"
"\n"
"QTabBar QToolButton::right-arrow:hover {\n"
"     image: url(icons/right_arrow_lighter.png);\n"
"}\n"
"\n"
" QTabBar QToolButton::left-arrow:enabled {\n"
"     image: url(icons/left_arrow_light.png);\n"
"}\n"
"\n"
" QTabBar QToolButton::left-arrow:disabled,\n"
" QTabBar QToolButton::left-arrow:off {\n"
"     image: url(icons/left_arrow_disabled_dark.png);\n"
"}\n"
"\n"
" QTabBar QToolButton::left-arrow:hover {\n"
"     image: url(icons/left_arrow_lighter.png);\n"
"}\n"
"\n"
" QTabBar QToolButton::up-arrow:enabled {\n"
"     image: url(icons/up_arrow_light.png);\n"
"}\n"
"\n"
" QTabBar QToolButton::up-arrow:disabled,\n"
" QTabBar QToolButton::up-arrow:off {\n"
"     image: url(icons/up_arrow_disabled_dark.png);\n"
"}\n"
"\n"
" QTabBar QToolButton::up-arrow:hover {\n"
"     image: url(icons/up_arrow_lighter.png);\n"
"}\n"
"\n"
" QTabBar QToolButton::d"
                        "own-arrow:enabled {\n"
"     image: url(icons/down_arrow_light.png);\n"
"}\n"
"\n"
" QTabBar QToolButton::down-arrow:disabled,\n"
" QTabBar QToolButton::down-arrow:off {\n"
"     image: url(icons/down_arrow_disabled_dark.png);\n"
"}\n"
"\n"
" QTabBar QToolButton::down-arrow:hover {\n"
"     image: url(icons/down_arrow_lighter.png);\n"
"}\n"
"\n"
"/* TOP and BOTTOM TABS */\n"
"QTabBar::tab:top,\n"
"QTabBar::tab:bottom {\n"
"    color: #c7c7c9;\n"
"    border: 1px solid #6d6e71;\n"
"    border-left-color: #85878a;\n"
"    border-right-width: 0px;\n"
"    background-color: #6d6e71;\n"
"    padding:5px 15px;\n"
"    margin-top: 4px;\n"
"    margin-bottom: 4px;\n"
"    position: center;\n"
"}\n"
"\n"
"QTabBar::tab:top:first,\n"
"QTabBar::tab:bottom:first {\n"
"    border-top-left-radius: 6px;\n"
"    border-bottom-left-radius: 6px;\n"
"}\n"
"\n"
"QTabBar::tab:top:last,\n"
"QTabBar::tab:bottom:last {\n"
"    border-top-right-radius: 6px;\n"
"    border-bottom-right-radius: 6px;\n"
"    border-right-width: 1px;\n"
"}"
                        "\n"
"\n"
"QTabBar::tab:top:selected,\n"
"QTabBar::tab:bottom:selected {\n"
"    color: white;\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.545, x2:1, y2:0, stop:0 #3874f2, stop:1 #5e90fa);\n"
"    border-color: #3874f2;\n"
"}\n"
"\n"
"QTabBar::tab:top:!selected:hover,\n"
"QTabBar::tab:bottom:!selected:hover {\n"
"    color: white;\n"
"}\n"
"\n"
"QTabBar::tab:top:only-one ,\n"
"QTabBar::tab:bottom:only-one {\n"
"    border: 1px solid #1b3774;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"/* LEFT and RIGHT TABS */\n"
"QTabBar::tab:left,\n"
"QTabBar::tab:right {\n"
"    color: #c7c7c9;\n"
"    border: 1px solid #6d6e71;\n"
"    border-top-color: #85878a;\n"
"    border-bottom-width: 0px;\n"
"    background-color: #6d6e71;\n"
"    padding: 15px 5px;\n"
"    margin-left: 4px;\n"
"    margin-right: 4px;\n"
"    position: center;\n"
"}\n"
"\n"
"QTabBar::tab:left:first,\n"
"QTabBar::tab:right:first {\n"
"    border-top-left-radius: 6px;\n"
"    border-top-right-radius: 6px;\n"
"}\n"
"\n"
"QTabBar::tab"
                        ":left:last,\n"
"QTabBar::tab:right:last {\n"
"    border-bottom-left-radius: 6px;\n"
"    border-bottom-right-radius: 6px;\n"
"    border-bottom-width: 1px;\n"
"}\n"
"\n"
"QTabBar::tab:left:selected,\n"
"QTabBar::tab:right:selected {\n"
"    color: white;\n"
"    background-color: qlineargradient(spread:pad, x1:0.545, y1:1, x2:0, y2:1, stop:0 #3874f2, stop:1 #5e90fa);\n"
"    border-color: #3874f2;\n"
"}\n"
"\n"
"QTabBar::tab:left:!selected:hover,\n"
"QTabBar::tab:right:!selected:hover {\n"
"    color: white;\n"
"}\n"
"\n"
"QTabBar::tab:left:only-one ,\n"
"QTabBar::tab:right:only-one {\n"
"    border: 1px solid #1b3774;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QDockWidget {\n"
"    color: #4d4e51;\n"
"    border: 1px solid #85878a;\n"
"    titlebar-close-icon: url(icons/close_dark.png);\n"
"    titlebar-normal-icon: url(icons/undock_dark.png);\n"
"}\n"
"\n"
"QDockWidget::title {\n"
"    text-align: center;\n"
"    background-color: #797b7f;\n"
"    padding: 4px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QDo"
                        "ckWidget::close-button,\n"
"QDockWidget::float-button {\n"
"    border: 1px transparent #85878a;\n"
"    border-radius: 2px;\n"
"    background: transparent;\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: right center;\n"
"}\n"
"\n"
"QDockWidget::close-button {\n"
"    right: 4px;\n"
"}\n"
"    \n"
"QDockWidget::float-button {\n"
"    right: 22px;\n"
"}\n"
"\n"
"QDockWidget::close-button:hover,\n"
"QDockWidget::float-button:hover {\n"
"    background: #9a9b9e;\n"
"}\n"
"\n"
"QDockWidget::close-button:pressed,\n"
"QDockWidget::float-button:pressed {\n"
"    /*padding: 1px -1px -1px 1px;*/\n"
"    background-color: #797b7f;\n"
"}\n"
"\n"
"QTreeView,\n"
"QListView {\n"
"    color: #4d4e51;\n"
"    border: 1px solid #85878a;\n"
"    border-radius: 4px;\n"
"    background-color: #bdc1c9;  /* related with alternate-background-color*/\n"
"    selection-color: white;\n"
"    selection-background-color: #5e90fa; /* should be similar to QListView::item selected background-color */\n"
"    show-decorati"
                        "on-selected: 1; /* make the selection span the entire width of the view */\n"
"    padding: 0px;\n"
"    margin: 0px 4px 0px 4px;\n"
"    min-width: 130px; /* hack to correctly align Preferences icon list  */\n"
"}\n"
"\n"
"QListView,\n"
"QListView::item,\n"
"QListView QAbstractItemView {\n"
"    margin: 0px;\n"
"    icon-size: 20px; /* temporal */\n"
"    paint-alternating-row-colors-for-empty-area: 1;\n"
"    position: absolute;\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: left top;\n"
"}\n"
"\n"
"/* Control dropdown list margins of QComboBox */\n"
"QComboBox QTreeView,\n"
"QComboBox QListView {\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"QListView::item {\n"
"    border: 0px transparent #85878a;\n"
"    border-radius: 4px;\n"
"    background-color: transparent;\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"    display: inline-block;\n"
"    position: relative;\n"
"}\n"
"\n"
"QListView::item:selected,\n"
"QTreeView::item:selected  {\n"
"    color: white;\n"
"    background-c"
                        "olor: #5e90fa; /* should be similar to QListView selection-background-color */\n"
"}\n"
"\n"
"/* Branch system */\n"
"QTreeView::branch  {\n"
"    background: transparent;\n"
"}\n"
"\n"
"QTreeView::branch:has-siblings:!adjoins-item  {\n"
"    border-image: url(icons/branch_vline.png) 0;\n"
"}\n"
"\n"
"QTreeView::branch:has-siblings:adjoins-item  {\n"
"    border-image: url(icons/branch_more.png) 0;\n"
"}\n"
"\n"
"QTreeView::branch:!has-children:!has-siblings:adjoins-item  {\n"
"    border-image: url(icons/branch_end.png) 0;\n"
"}\n"
"\n"
"QTreeView::branch:closed:has-children:has-siblings  {\n"
"    image: url(icons/branch_closed_dark.png);\n"
"}\n"
"\n"
"QTreeView::branch:has-children:!has-siblings:closed  {\n"
"    image: url(icons/branch_closed_dark.png);\n"
"    border-image: url(icons/branch_end.png) 0;\n"
"}\n"
"\n"
"QTreeView::branch:open:has-children:has-siblings  {\n"
"    image: url(icons/branch_open_dark.png);\n"
"    border-image: url(icons/branch_more.png) 0;\n"
"}\n"
"\n"
"QTreeView::branch:open:"
                        "has-children:!has-siblings  {\n"
"    image: url(icons/branch_open_dark.png);\n"
"    border-image: url(icons/branch_end.png) 0;\n"
"}\n"
"\n"
"QSlider,\n"
"QSlider:active,\n"
"QSlider:!active {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QSlider:horizontal {\n"
"    padding: 0px 10px;\n"
"}\n"
"\n"
"QSlider:vertical {\n"
"    padding: 10px 0px;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"    border: 1px solid #6d6e71;\n"
"    background-color: #6d6e71;\n"
"    height: 8px;\n"
"    border-radius: 5px;\n"
"    margin: 4px 0;\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"    border: 1px solid #6d6e71;\n"
"    background-color: #6d6e71;\n"
"    width: 8px;\n"
"    border-radius: 5px;\n"
"    margin: 4px 0;\n"
"}\n"
"\n"
"QSlider::groove:horizontal:disabled,\n"
"QSlider::groove:vertical:disabled {\n"
"    border-color:  #797b7f;\n"
"    background-color: #797b7f;\n"
"}\n"
"\n"
"QSlider::handle:horizontal,\n"
"QSlider::handle:vertical {\n"
"    background-color: #4d4e51;\n"
"    "
                        "border: 1px solid #4d4e51;\n"
"    width: 14px;\n"
"    height: 14px;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    margin: -4px 0;\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"    margin: 0 -4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover,\n"
"QSlider::handle:vertical:hover {\n"
"    border-color: #3874f2;\n"
"    background-color: #3874f2;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:pressed,\n"
"QSlider::handle:vertical:pressed {\n"
"    border-color: #1b3774;\n"
"    background-color: #1b3774;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:disabled,\n"
"QSlider::handle:vertical:disabled {\n"
"    border-color: #6d6e71;\n"
"    background-color: #85878a;\n"
"}\n"
"\n"
"QToolButton {\n"
"    color: #c7c7c9;\n"
"    text-align: center;\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.545, x2:1, y2:0, stop:0 #6d6e71, stop:1 #85878a);\n"
"    border: 1px solid #4d4e51;\n"
"    padding-top: 5px;\n"
"    padding-bottom: 5px;\n"
"    padding-left: 15px;\n"
"    paddi"
                        "ng-right: 15px;\n"
"    margin-top: 5px;\n"
"    margin-bottom: 5px;\n"
"    margin-left: 10px;\n"
"    margin-right: 10px;\n"
"    border-radius: 3px;\n"
"    outline: none;\n"
"}\n"
"\n"
"QToolButton:hover,\n"
"QToolButton:focus {\n"
"    color: white;\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.545, x2:1, y2:0, stop:0 #3874f2, stop:1 #5e90fa);\n"
"    border-color: #3874f2;\n"
"}\n"
"\n"
"QToolButton:disabled,\n"
"QToolButton:disabled:checked {\n"
"    color: #6d6e71;\n"
"    background-color: #85878a;\n"
"    border-color: #6d6e71;\n"
"}\n"
"\n"
"QToolButton:pressed {\n"
"    border-color: #7cabf9;\n"
"}\n"
"\n"
"QToolButton:checked {\n"
"    background-color: #5e90fa;\n"
"    border-color: #3874f2;\n"
"}\n"
"\n"
"QToolButton::menu-indicator  {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: center right;\n"
"    right: 4px;\n"
"}\n"
"\n"
"/*The \"show more\" button  (it can also be stylable with \"QToolBarExtension\" */\n"
"QToolButton#qt_toolbar_ext_button {\n"
"    "
                        "border-radius: 0px;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"    /*background-image: url(icons/more_dark.png);*/\n"
"    image: transparent;\n"
"    background-repeat: none;\n"
"    background-position: center left;\n"
"}\n"
"\n"
"QToolButton#qt_toolbar_ext_button:hover {\n"
"    /*background-image: url(icons/more_light.png);*/\n"
"    border-color: #797b7f;\n"
"    background-color: #797b7f;\n"
"}\n"
"\n"
"QToolButton#qt_toolbar_ext_button:on {\n"
"    /*background-image: url(icons/more_light.png);*/\n"
"    border-color: #797b7f;\n"
"    background-color: #797b7f;\n"
"}\n"
"\n"
"/*Buttons inside the Toolbar*/\n"
"QToolBar QToolButton {\n"
"    color: #4d4e51;\n"
"    background-color: #85878a;\n"
"    border: 1px transparent #85878a;\n"
"    border-radius: 3px;\n"
"    margin: 0px;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QToolBar QToolButton:disabled {\n"
"    background-color: #85878a;\n"
"}\n"
"\n"
"QToolBar QToolButton:checked {\n"
"    color: #1b3774;\n"
"    background-color: #5e90fa;\n"
"    border:"
                        " 1px solid #5e90fa;\n"
"}\n"
"\n"
"QToolBar QToolButton:hover {\n"
"    background-color: #85878a;\n"
"}\n"
"\n"
"QToolBar QToolButton:pressed,\n"
"QToolBar QToolButton::menu-button:pressed {\n"
"    background-color: #797b7f;\n"
"    border: 1px solid #797b7f;\n"
"}\n"
"\n"
"\n"
"QToolBar QToolButton::menu-indicator:hover,\n"
"QToolBar QToolButton::menu-indicator:pressed {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"/* the subcontrols below are used only in the MenuButtonPopup mode */\n"
"QToolBar QToolButton::menu-button {\n"
"    border: 1px transparent #4A4949;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"    width: 16px; /* 16px width + 4px for border = 20px allocated above */\n"
"    outline: none;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QToolBar QToolButton::menu-button:hover,\n"
"QToolBar QToolButton::menu-button:active,\n"
"QToolBar QToolButton::menu-button:disabled {\n"
"    border-color: transparent;\n"
"    background-color: transparent;"
                        "\n"
"}\n"
"\n"
"QToolBar QToolButton::menu-arrow {\n"
"    background-image: url(icons/down_arrow_light.png);\n"
"    background-position: center center;\n"
"    background-repeat: none;\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: bottom right;\n"
"    height: 10px; /* same as arrow image */\n"
"}\n"
"\n"
"QToolBar QToolButton::menu-arrow:open {\n"
"    background-image: url(icons/down_arrow_lighter.png);\n"
"}\n"
"\n"
"QToolBar:tear {\n"
"    color: blue;\n"
"    background-color: red;\n"
"}\n"
"\n"
"QTableView {\n"
"    color: #4d4e51;\n"
"    border: 1px solid #6d6e71;\n"
"    gridline-color: #9a9b9e;\n"
"    background-color: #bdc1c9;\n"
"    selection-color: #4d4e51;\n"
"    selection-background-color: #adc5ed;\n"
"    border-radius: 3px;\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QTableView::item:hover  {\n"
"    background: #abb0b7;\n"
"}\n"
"\n"
"QTableView::item:disabled  {\n"
"    color: #85878a;\n"
"}\n"
"\n"
"QTableView::item:selected  {\n"
"    color: #1b3774;\n"
""
                        "    background-color: #7cabf9;\n"
"}\n"
"\n"
"/* when editing a cell: */\n"
"QTableView QLineEdit {\n"
"    color: #4d4e51;\n"
"    background-color: #b3b8bf;\n"
"    border-radius: 0px;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"QHeaderView {\n"
"    border: none;\n"
"    background-color: #4d4e51;\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"QHeaderView::section  {\n"
"    background-color: transparent;\n"
"    color: #c7c7c9;\n"
"    border: 1px solid transparent;\n"
"    border-radius: 0px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QHeaderView::section::vertical  {\n"
"    padding: 0px 6px 0px 6px;\n"
"    border-bottom: 1px solid #6d6e71;\n"
"}\n"
"\n"
"QHeaderView::section::vertical:first {\n"
"    border-top: 1px solid  #6d6e71;\n"
"}\n"
"\n"
"QHeaderView::section::vertical:last {\n"
"    border-bottom: none;\n"
"}\n"
"\n"
""
                        "QHeaderView::section::vertical:only-one {\n"
"    border: none;\n"
"}\n"
"\n"
"QHeaderView::section::horizontal  {\n"
"    padding: 0px 0px 0px 6px;\n"
"    border-right: 1px solid #6d6e71;\n"
"}\n"
"\n"
"QHeaderView::section::horizontal:first {\n"
"    border-left: 1px solid #6d6e71;\n"
"}\n"
"\n"
"QHeaderView::section::horizontal:last {\n"
"    border-left: none;\n"
"}\n"
"\n"
"QHeaderView::section::horizontal:only-one {\n"
"    border: none;\n"
"}\n"
"\n"
"QDockWidget QHeaderView::section {\n"
"    border-width: 6px 1px 6px 1px; /* hack to bigger margin for Model Panel table headers */\n"
"}\n"
"\n"
"QHeaderView::section:checked {\n"
"    color: #1b3774;\n"
"    background-color: #7cabf9;\n"
"}\n"
"\n"
" /* style the sort indicator */\n"
"QHeaderView::down-arrow {\n"
"    image: url(icons/down_arrow_light.png);\n"
"}\n"
"\n"
"QHeaderView::up-arrow {\n"
"    image: url(icons/up_arrow_light.png);\n"
"}\n"
"\n"
"QTableCornerButton::section {\n"
"    background-color: #4d4e51;\n"
"    border: 1px solid #4d4e51;"
                        "\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"QToolBox  {\n"
"    padding: 3px;\n"
"    color: #1b3774;\n"
"    border: none;\n"
"}\n"
"\n"
"QToolBox::tab { /* TODO */\n"
"    color: #c7c7c9;\n"
"    background-color: #6d6e71;\n"
"    border: 1px transparent #4d4e51;\n"
"    border-bottom: 1px transparent #6d6e71;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QToolBox::tab:selected { /* italicize selected tabs */\n"
"    color: #1b3774;\n"
"    font: italic;\n"
"    background-color: #5e90fa;\n"
"    border-color: #5e90fa;\n"
" }\n"
"\n"
"QStatusBar::item {\n"
"    color: #c7c7c9;\n"
"    background-color: #85878a;\n"
"    border: 1px solid #85878a;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSplitter::handle {\n"
"    background-color: #85878a;\n"
"    margin: 0px 11px;\n"
"    padding: 0px;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QSplitter::handle:vertical {\n"
"    background-image: url(icons/splitter_horizontal_dark.png);\n"
"    background"
                        "-position: center center;\n"
"    background-repeat: none;\n"
"    margin: 2px 10px 2px 10px;\n"
"    height: 2px;\n"
"}\n"
"\n"
"QSplitter::handle:horizontal {\n"
"    background-image: url(icons/splitter_horizontal_dark.png);\n"
"    background-position: center center;\n"
"    background-repeat: none;\n"
"    margin: 10px 2px 10px 2px;\n"
"    width: 2px;\n"
"}\n"
"\n"
"QSplitter::handle:horizontal:hover,\n"
"QSplitter::handle:vertical:hover {\n"
"    background-color: #85878a;\n"
"}\n"
"\n"
"/* Similar to the splitter is the following window separator: */\n"
"QMainWindow::separator {\n"
"    border: 1px solid #85878a;\n"
"    background-color: #85878a;\n"
"    background-position: center center;\n"
"    background-repeat: none;\n"
"}\n"
"\n"
"QMainWindow::separator:hover {\n"
"    background-color: #85878a;\n"
"}\n"
"\n"
"QMainWindow::separator:horizontal {\n"
"    height: 4px;\n"
"    background-image: url(icons/splitter_horizontal_dark.png);\n"
"}\n"
"\n"
"QMainWindow::separator:vertical {\n"
"    width: "
                        "4px;\n"
"    background-image: url(icons/splitter_vertical_dark.png);\n"
"}\n"
"\n"
"QLabel {\n"
"    padding-top: 3px;\n"
"    padding-bottom: 3px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QLabel:disabled {\n"
"    color: #6d6e71;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"/* Action group */\n"
"QFrame[class=\"panel\"] {\n"
"    border: none;\n"
"    background-color: #85878a;\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"header\"] {\n"
"    border: none;\n"
"    background-color: #4d4e51;\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"header\"]:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.545, x2:1, y2:0, stop:0 #3874f2, stop:1 #5e90fa);\n"
"}\n"
"\n"
"QSint--ActionGroup QToolButton[class=\"header\"] {\n"
"    text-align: left;\n"
"    font-weight: bold;\n"
""
                        "    color: #c7c7c9;\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"QSint--ActionGroup QToolButton[class=\"header\"]:hover {\n"
"    color: white;\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"header\"] QLabel {\n"
"    background-color: transparent;\n"
"    background-image: url(icons/down_arrow_light.png);\n"
"    background-repeat: none;\n"
"    background-position: center center;\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"header\"] QLabel:hover {\n"
"    background-color: transparent;\n"
"    background-image: url(icons/down_arrow_lighter.png);\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"header\"] QLabel[fold=\"true\"] {\n"
"    background-color: transparent;\n"
"    background-image: url(icons/up_arrow_light.png);\n"
"    background-repeat: none;\n"
"    background-position: center center;\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\""
                        "header\"] QLabel[fold=\"true\"]:hover {\n"
"    background-color: transparent;\n"
"    background-image: url(icons/up_arrow_lighter.png);\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"content\"] {\n"
"    background-color: #bdc1c9;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"    border: none;\n"
"    border-top-left-radius: 0px;\n"
"    border-top-right-radius: 0px;\n"
"    border-bottom-left-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"/* HACK\n"
"This might not be the best way to reset the background color: */\n"
"QSint--ActionGroup QFrame[class=\"content\"] QWidget {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"content\"] QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.545, x2:1, y2:0, stop:0 #6d6e71, stop:1 #85878a);\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"content\"] QPushButton:hover,\n"
"QSint--ActionGroup QFrame[class=\"content\"] QPushButton:focus {\n"
"    background-color: qlineargradient("
                        "spread:pad, x1:1, y1:0.545, x2:1, y2:0, stop:0 #3874f2, stop:1 #5e90fa);\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"content\"] QPushButton:disabled,\n"
"QSint--ActionGroup QFrame[class=\"content\"] QPushButton:disabled:checked {\n"
"    color: #bdc1c9;\n"
"    border-color: #9a9b9e;\n"
"    background-color: #9a9b9e;\n"
"}\n"
"QSint--ActionGroup QFrame[class=\"content\"] QPushButton:checked {\n"
"    background-color: #5e90fa;\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"content\"] QComboBox {\n"
"    background-color: #6d6e71;\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"content\"] QComboBox:on {\n"
"    background-color: #6d6e71;\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"content\"] QComboBox QAbstractItemView {\n"
"    border-color: #4d4e51;\n"
"    background-color: #4d4e51;\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"content\"] QListView {\n"
"    border-color: #abb0b7;\n"
"    background-color: #abb0b7;\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"content\"] QAbstractSpinBox "
                        "{\n"
"    background-color: #6d6e71;\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"content\"] QLineEdit {\n"
"    background-color: #6d6e71;\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"content\"] QComboBox:disabled,\n"
"QSint--ActionGroup QFrame[class=\"content\"] QAbstractSpinBox:disabled,\n"
"QSint--ActionGroup QFrame[class=\"content\"] QLineEdit:disabled {\n"
"    color: #bdc1c9;\n"
"    border-color: #9a9b9e;\n"
"    background-color: #9a9b9e;\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"content\"] QCheckBox:disabled,\n"
"QSint--ActionGroup QFrame[class=\"content\"] QRadioButton:disabled {\n"
"    color: #9a9b9e;\n"
"    border-color: #9a9b9e;\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"content\"] QCheckBox::indicator:disabled,\n"
"QSint--ActionGroup QFrame[class=\"content\"] QRadioButton::indicator:disabled {\n"
"    border-color: #9a9b9e;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"content\"] QHeaderView {\n"
"    border: none;\n"
"    backgrou"
                        "nd-color: #4d4e51;\n"
"    border-radius: 0px;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"content\"] QHeaderView::section  {\n"
"    background-color: transparent;\n"
"    color: #c7c7c9;\n"
"    border: 1px solid transparent;\n"
"    border-radius: 0px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"content\"] QHeaderView::section::horizontal  {\n"
"    padding: 6px 0px 6px 6px;\n"
"    border-right: 1px solid #6d6e71;\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"content\"] QHeaderView::section::horizontal:first {\n"
"    border-left: 1px solid #85878a;\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"content\"] QHeaderView::section::horizontal:last {\n"
"    border-left: none;\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"content\"] QHeaderView::section::horizontal:only-one {\n"
"    border: none;\n"
"}\n"
"/* enf of HACK */\n"
"\n"
"QSint--ActionGroup QToolButton[class=\"action\"],\n"
"QSint--ActionGroup QToolButton[class="
                        "\"action\"]:enabled {\n"
"    font-weight: bold;\n"
"    color: #6d6e71;\n"
"}\n"
"\n"
"QSint--ActionGroup QToolButton[class=\"action\"]:hover,\n"
"QSint--ActionGroup QToolButton[class=\"action\"]:enabled:hover {\n"
"    text-decoration: none;\n"
"    color: #4d4e51;\n"
"    background-color: #abb0b7;\n"
"    border-color: #abb0b7;\n"
"}\n"
"\n"
"QSint--ActionGroup QToolButton[class=\"action\"]:disabled {\n"
"    color: #85878a;\n"
"    background-color: #abb0b7;\n"
"    border-color: #abb0b7;\n"
"}\n"
"\n"
"QSint--ActionGroup QToolButton[class=\"action\"]:focus,\n"
"QSint--ActionGroup QToolButton[class=\"action\"]:pressed\n"
"QSint--ActionGroup QToolButton[class=\"action\"]:enabled:focus,\n"
"QSint--ActionGroup QToolButton[class=\"action\"]:enabled:pressed {\n"
"    color: white;\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.545, x2:1, y2:0, stop:0 #3874f2, stop:1 #5e90fa);\n"
"    border-color: #3874f2;\n"
"}\n"
"\n"
"QSint--ActionGroup QToolButton[class=\"action\"]:on {\n"
"    background"
                        "-color: red;\n"
"    color: red;\n"
"}")
        self.actionaha = QAction(MainWindow)
        self.actionaha.setObjectName(u"actionaha")
        self.actionuwwu = QAction(MainWindow)
        self.actionuwwu.setObjectName(u"actionuwwu")
        self.actionmore_uwwu = QAction(MainWindow)
        self.actionmore_uwwu.setObjectName(u"actionmore_uwwu")
        self.actionswlowly = QAction(MainWindow)
        self.actionswlowly.setObjectName(u"actionswlowly")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.widget = AnalogGaugeWidget(self.centralwidget)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(40, 70, 381, 291))
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(510, 200, 181, 41))
        self.pushButton.setStyleSheet(u"")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 23))
        self.menutest1 = QMenu(self.menubar)
        self.menutest1.setObjectName(u"menutest1")
        self.menuuwu = QMenu(self.menutest1)
        self.menuuwu.setObjectName(u"menuuwu")
        self.menudo_not_click = QMenu(self.menubar)
        self.menudo_not_click.setObjectName(u"menudo_not_click")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menutest1.menuAction())
        self.menubar.addAction(self.menudo_not_click.menuAction())
        self.menutest1.addAction(self.actionaha)
        self.menutest1.addAction(self.actionswlowly)
        self.menutest1.addAction(self.menuuwu.menuAction())
        self.menuuwu.addAction(self.actionuwwu)
        self.menuuwu.addAction(self.actionmore_uwwu)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionaha.setText(QCoreApplication.translate("MainWindow", u"fasterrrr", None))
        self.actionuwwu.setText(QCoreApplication.translate("MainWindow", u"uwwu", None))
        self.actionmore_uwwu.setText(QCoreApplication.translate("MainWindow", u"more uwwu", None))
        self.actionswlowly.setText(QCoreApplication.translate("MainWindow", u"swlowly :(", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"stop pls", None))
        self.menutest1.setTitle(QCoreApplication.translate("MainWindow", u"test1", None))
        self.menuuwu.setTitle(QCoreApplication.translate("MainWindow", u"uwu", None))
        self.menudo_not_click.setTitle(QCoreApplication.translate("MainWindow", u"do not click", None))
    # retranslateUi

